#!/usr/bin/env python3
"""Assemble extracted original-Colonization PNGs into a local FreeCol mod pack.

Part of the classic-UI "bring-your-own-install" asset pipeline (see
CLASSIC_UI_PLAN.md, "Asset strategy").  Invoked by the Ant ``classic-assets``
target *after* mpskit has unpacked the user's own ``.SS`` / ``.PIK`` art to PNG.

This script ships nothing itself: it only arranges the locally-generated PNGs
and writes a ``resources.properties`` exposing every frame under a stable
``image.classic_original.*`` key namespace, plus a ``mod.xml``.  Mapping the
real FreeCol resource keys onto these (plan item A2) is kept in the committed
``aliases.properties`` next to this script and appended here if present, so the
regenerated (git-ignored) pack never clobbers that hand-maintained work.

The file itself contains no copyrighted content and is safe to commit; its
*output* (the pack under data/mods/classic_original/) is git-ignored.
"""

import argparse
import os
import shutil


def collect(src_dir, out_img_dir, key_prefix, rel_prefix):
    """Copy every ``*.png`` from *src_dir* into *out_img_dir*.

    Returns an ordered ``{resource-key: relative-path}`` dict.  We enumerate the
    PNGs mpskit actually produced rather than predicting their names, so we are
    robust to its ``NAME.png`` (pik) vs ``NAME.000.png`` (ss) conventions.
    Non-image outputs (``.json`` sprite headers etc.) are ignored.
    """
    entries = {}
    if not os.path.isdir(src_dir):
        return entries
    os.makedirs(out_img_dir, exist_ok=True)
    for name in sorted(os.listdir(src_dir)):
        if not name.lower().endswith(".png"):
            continue
        shutil.copyfile(os.path.join(src_dir, name),
                        os.path.join(out_img_dir, name))
        stem = name[:-4]  # drop ".png"
        entries["{}.{}".format(key_prefix, stem)] = "{}/{}".format(rel_prefix, name)
    return entries


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--ss", required=True, help="dir of unpacked .SS PNGs")
    ap.add_argument("--pik", required=True, help="dir of unpacked .PIK PNGs")
    ap.add_argument("--out", required=True, help="mod pack output dir")
    args = ap.parse_args()

    out = args.out
    img_root = os.path.join(out, "resources", "images")

    # Regenerate cleanly (the pack is a build artifact).
    if os.path.isdir(out):
        shutil.rmtree(out)
    os.makedirs(img_root, exist_ok=True)

    entries = {}
    entries.update(collect(args.pik, os.path.join(img_root, "pik"),
                           "image.classic_original.pik", "resources/images/pik"))
    entries.update(collect(args.ss, os.path.join(img_root, "ss"),
                           "image.classic_original.ss", "resources/images/ss"))

    # resources.properties: scaffold keys, then optional A2 aliases.
    props_path = os.path.join(out, "resources.properties")
    with open(props_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("# GENERATED by tools/classic_assets/build_pack.py -- do not edit by hand.\n")
        f.write("# Local pack of the user's OWN original Colonization art (git-ignored).\n")
        f.write("# Scaffold keys expose every extracted frame; FreeCol-key aliases\n")
        f.write("# (plan item A2) are appended from tools/classic_assets/aliases.properties.\n\n")
        for key in sorted(entries):
            f.write("{}={}\n".format(key, entries[key]))

        aliases = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                               "aliases.properties")
        if os.path.isfile(aliases):
            f.write("\n# --- A2 aliases (from tools/classic_assets/aliases.properties) ---\n")
            with open(aliases, "r", encoding="utf-8") as a:
                f.write(a.read())

    with open(os.path.join(out, "mod.xml"), "w", encoding="utf-8", newline="\n") as f:
        f.write('<mod id="classic_original"/>\n')

    with open(os.path.join(out, "FreeColMessages.properties"),
              "w", encoding="utf-8", newline="\n") as f:
        f.write("mod.classic_original.name=Classic Colonization art (local)\n")
        f.write("mod.classic_original.shortDescription="
                "Original Sid Meier's Colonization graphics, extracted locally "
                "from your own game install.\n")

    n_pik = sum(1 for k in entries if k.startswith("image.classic_original.pik."))
    n_ss = len(entries) - n_pik
    print("classic_original pack: {} pik + {} ss images -> {}".format(n_pik, n_ss, out))


if __name__ == "__main__":
    main()
